services:
  - type: web
    name: ai-wrapperz
    runtime: python
    buildCommand: pip install pipenv && pipenv install --deploy
    startCommand: pipenv run gunicorn run:app -b 0.0.0.0:${PORT}
    envVars:
      - key: PYTHON_VERSION
        value: 3.12
